"""update_product_tier_relationships

Revision ID: 39f3d1d2ebf6
Revises: 
Create Date: 2024-11-04 10:46:39.040970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39f3d1d2ebf6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stripe_price_id')
    op.drop_column('products', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('stripe_price_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
